[style.description]
underline = false
bold = false

[style.command_name]
foreground = "cyan"
underline = false
bold = false

[style.example_text]
foreground = "green"
underline = false
bold = false

[style.example_code]
foreground = "cyan"
underline = false
bold = false

[style.example_variable]
foreground = "cyan"
underline = true
bold = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 720
