name: Test THT Release

on:
  # Run if the test files are updated
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yml'
      - 'test/**'
  # Run if a new THT image is pushed to ghcr.io
  registry_package:
    action:
      - published

jobs:
  test:
    name: Run BATS tests
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - 
      name: BATS 
      env:
        # Use Github Container Registry THT image
        IMAGE: ghcr.io/ethack/tht:latest
      run: |
        ./tht -c "cat /etc/tht-release"
        ./tht --dev -c "/usr/local/test/bats/bin/bats /usr/local/test"